### ISSUE TITLE
Wrong configuration of typings for *.mjs

### ISSUE THREAD

**Issue by jsardev** [patdx/zustand-rx#944]
When someone's using your module as ESM module (*.mjs), the typings are not configured properly, resulting in warnings like this:

![CleanShot 2023-11-09 at 09 56 25](https://github.com/patdx/zustand-rx/assets/11553624/ae2c7fd6-0c5b-48be-904f-0210e43a6509)

I think it can be fixed by configuring the typings specificaly for import/require, like this: https://github.com/gxmari007/vite-plugin-eslint/pull/60/files

**Comment by patdx** [comment]
Hi @jsardev, thanks for the report.

I made some updates and released a new version 2.0.0. The main change is an updated package output format to work with the new TS module resolution modes. I also confirmed it via "Are The Types Wrong":

https://arethetypeswrong.github.io/?p=zustand-rx%402.0.0

![image](https://github.com/patdx/zustand-rx/assets/353863/d59f9648-11f2-4e8b-96f5-dbd189bb91c2)

I hope you can give it a try when you have a chance. If you still have issues could you please share your tsconfig `module` and `moduleResolution` values to help me reproduce the issue. Thanks!

**Comment by jsardev** [comment]
@patdx Thank you! This issue has been resolved :)
