### ISSUE TITLE
Types are lost when used with immer

### ISSUE THREAD

**Issue by jsardev** [patdx/zustand-rx#953]
When you use a Zustand store with [immer middleware](https://docs.pmnd.rs/zustand/integrations/immer-middleware), `toStream` loses types for `state` in the callback function (it ends up as `object`).

![CleanShot 2023-11-29 at 20 37 21](https://github.com/patdx/zustand-rx/assets/11553624/662f0523-f864-4ad1-bd00-be936bebd83e)

Here's a quick reproduction sandbox: https://codesandbox.io/p/sandbox/dreamy-euler-xnjnc5?file=/src/App.tsx:7,17

**Comment by patdx** [comment]
I just published a new version 2.1.0. I think it should be fixed there. If you have a chance please try it out. Thanks!
